class Country {
  final int id;
  final String name;
  final String flag;

  const Country(this.id, this.name, this.flag);
}

const List<Country> countries = [
  Country(0, 'Não Informado', '❓'),
  Country(1, 'Afeganistão', '🇦🇫'),
  Country(2, 'África do Sul', '🇿🇦'),
  Country(3, 'Albânia', '🇦🇱'),
  Country(4, 'Alemanha', '🇩🇪'),
  Country(5, 'Andorra', '🇦🇩'),
  Country(6, 'Angola', '🇦🇴'),
  Country(7, 'Antígua e Barbuda', '🇦🇬'),
  Country(8, 'Arábia Saudita', '🇸🇦'),
  Country(9, 'Argélia', '🇩🇿'),
  Country(10, 'Argentina', '🇦🇷'),
  Country(11, 'Armênia', '🇦🇲'),
  Country(12, 'Austrália', '🇦🇺'),
  Country(13, 'Áustria', '🇦🇹'),
  Country(14, 'Azerbaijão', '🇦🇿'),
  Country(15, 'Bahamas', '🇧🇸'),
  Country(16, 'Bangladesh', '🇧🇩'),
  Country(17, 'Barbados', '🇧🇧'),
  Country(18, 'Barein', '🇧🇭'),
  Country(19, 'Belarus', '🇧🇾'),
  Country(20, 'Bélgica', '🇧🇪'),
  Country(21, 'Belize', '🇧🇿'),
  Country(22, 'Benin', '🇧🇯'),
  Country(23, 'Bolívia', '🇧🇴'),
  Country(24, 'Bósnia e Herzegovina', '🇧🇦'),
  Country(25, 'Botsuana', '🇧🇼'),
  Country(26, 'Brasil', '🇧🇷'),
  Country(27, 'Brunei', '🇧🇳'),
  Country(28, 'Bulgária', '🇧🇬'),
  Country(29, 'Burkina Faso', '🇧🇫'),
  Country(30, 'Burundi', '🇧🇮'),
  Country(31, 'Butão', '🇧🇹'),
  Country(32, 'Cabo Verde', '🇨🇻'),
  Country(33, 'Camarões', '🇨🇲'),
  Country(34, 'Camboja', '🇰🇭'),
  Country(35, 'Canadá', '🇨🇦'),
  Country(36, 'Catar', '🇶🇦'),
  Country(37, 'Cazaquistão', '🇰🇿'),
  Country(38, 'Chade', '🇹🇩'),
  Country(39, 'Chile', '🇨🇱'),
  Country(40, 'China', '🇨🇳'),
  Country(41, 'Chipre', '🇨🇾'),
  Country(42, 'Colômbia', '🇨🇴'),
  Country(43, 'Comores', '🇰🇲'),
  Country(44, 'Congo', '🇨🇬'),
  Country(45, 'Coreia do Norte', '🇰🇵'),
  Country(46, 'Coreia do Sul', '🇰🇷'),
  Country(47, 'Costa do Marfim', '🇨🇮'),
  Country(48, 'Costa Rica', '🇨🇷'),
  Country(49, 'Croácia', '🇭🇷'),
  Country(50, 'Cuba', '🇨🇺'),
  Country(51, 'Dinamarca', '🇩🇰'),
  Country(52, 'Djibuti', '🇩🇯'),
  Country(53, 'Dominica', '🇩🇲'),
  Country(54, 'Egito', '🇪🇬'),
  Country(55, 'El Salvador', '🇸🇻'),
  Country(56, 'Emirados Árabes Unidos', '🇦🇪'),
  Country(57, 'Equador', '🇪🇨'),
  Country(58, 'Eritreia', '🇪🇷'),
  Country(59, 'Eslováquia', '🇸🇰'),
  Country(60, 'Eslovênia', '🇸🇮'),
  Country(61, 'Espanha', '🇪🇸'),
  Country(62, 'Estados Unidos', '🇺🇸'),
  Country(63, 'Estônia', '🇪🇪'),
  Country(64, 'Eswatini', '🇸🇿'),
  Country(65, 'Etiópia', '🇪🇹'),
  Country(66, 'Fiji', '🇫🇯'),
  Country(67, 'Filipinas', '🇵🇭'),
  Country(68, 'Finlândia', '🇫🇮'),
  Country(69, 'França', '🇫🇷'),
  Country(70, 'Gabão', '🇬🇦'),
  Country(71, 'Gâmbia', '🇬🇲'),
  Country(72, 'Gana', '🇬🇭'),
  Country(73, 'Geórgia', '🇬🇪'),
  Country(74, 'Granada', '🇬🇩'),
  Country(75, 'Grécia', '🇬🇷'),
  Country(76, 'Guatemala', '🇬🇹'),
  Country(77, 'Guiana', '🇬🇾'),
  Country(78, 'Guiné', '🇬🇳'),
  Country(79, 'Guiné-Bissau', '🇬🇼'),
  Country(80, 'Guiné Equatorial', '🇬🇶'),
  Country(81, 'Haiti', '🇭🇹'),
  Country(82, 'Honduras', '🇭🇳'),
  Country(83, 'Hungria', '🇭🇺'),
  Country(84, 'Iêmen', '🇾🇪'),
  Country(85, 'Ilhas Marshall', '🇲🇭'),
  Country(86, 'Ilhas Salomão', '🇸🇧'),
  Country(87, 'Índia', '🇮🇳'),
  Country(88, 'Indonésia', '🇮🇩'),
  Country(89, 'Irã', '🇮🇷'),
  Country(90, 'Iraque', '🇮🇶'),
  Country(91, 'Irlanda', '🇮🇪'),
  Country(92, 'Islândia', '🇮🇸'),
  Country(93, 'Israel', '🇮🇱'),
  Country(94, 'Itália', '🇮🇹'),
  Country(95, 'Jamaica', '🇯🇲'),
  Country(96, 'Japão', '🇯🇵'),
  Country(97, 'Jordânia', '🇯🇴'),
  Country(98, 'Kiribati', '🇰🇮'),
  Country(99, 'Kuwait', '🇰🇼'),
  Country(100, 'Laos', '🇱🇦'),
  Country(101, 'Lesoto', '🇱🇸'),
  Country(102, 'Letônia', '🇱🇻'),
  Country(103, 'Líbano', '🇱🇧'),
  Country(104, 'Libéria', '🇱🇷'),
  Country(105, 'Líbia', '🇱🇾'),
  Country(106, 'Liechtenstein', '🇱🇮'),
  Country(107, 'Lituânia', '🇱🇹'),
  Country(108, 'Luxemburgo', '🇱🇺'),
  Country(109, 'Macedônia do Norte', '🇲🇰'),
  Country(110, 'Madagascar', '🇲🇬'),
  Country(111, 'Malásia', '🇲🇾'),
  Country(112, 'Malaui', '🇲🇼'),
  Country(113, 'Maldivas', '🇲🇻'),
  Country(114, 'Mali', '🇲🇱'),
  Country(115, 'Malta', '🇲🇹'),
  Country(116, 'Marrocos', '🇲🇦'),
  Country(117, 'Maurício', '🇲🇺'),
  Country(118, 'Mauritânia', '🇲🇷'),
  Country(119, 'México', '🇲🇽'),
  Country(120, 'Micronésia', '🇫🇲'),
  Country(121, 'Moçambique', '🇲🇿'),
  Country(122, 'Moldávia', '🇲🇩'),
  Country(123, 'Mônaco', '🇲🇨'),
  Country(124, 'Mongólia', '🇲🇳'),
  Country(125, 'Montenegro', '🇲🇪'),
  Country(126, 'Mianmar', '🇲🇲'),
  Country(127, 'Namíbia', '🇳🇦'),
  Country(128, 'Nauru', '🇳🇷'),
  Country(129, 'Nepal', '🇳🇵'),
  Country(130, 'Nicarágua', '🇳🇮'),
  Country(131, 'Níger', '🇳🇪'),
  Country(132, 'Nigéria', '🇳🇬'),
  Country(133, 'Noruega', '🇳🇴'),
  Country(134, 'Nova Zelândia', '🇳🇿'),
  Country(135, 'Omã', '🇴🇲'),
  Country(136, 'Países Baixos', '🇳🇱'),
  Country(137, 'Palau', '🇵🇼'),
  Country(138, 'Panamá', '🇵🇦'),
  Country(139, 'Papua-Nova Guiné', '🇵🇬'),
  Country(140, 'Paquistão', '🇵🇰'),
  Country(141, 'Paraguai', '🇵🇾'),
  Country(142, 'Peru', '🇵🇪'),
  Country(143, 'Polônia', '🇵🇱'),
  Country(144, 'Portugal', '🇵🇹'),
  Country(145, 'Quênia', '🇰🇪'),
  Country(146, 'Quirguistão', '🇰🇬'),
  Country(147, 'Reino Unido', '🇬🇧'),
  Country(148, 'República Centro-Africana', '🇨🇫'),
  Country(149, 'República Checa', '🇨🇿'),
  Country(150, 'República Democrática do Congo', '🇨🇩'),
  Country(151, 'República Dominicana', '🇩🇴'),
  Country(152, 'Romênia', '🇷🇴'),
  Country(153, 'Ruanda', '🇷🇼'),
  Country(154, 'Rússia', '🇷🇺'),
  Country(155, 'Samoa', '🇼🇸'),
  Country(156, 'San Marino', '🇸🇲'),
  Country(157, 'Santa Lúcia', '🇱🇨'),
  Country(158, 'São Cristóvão e Nevis', '🇰🇳'),
  Country(159, 'São Tomé e Príncipe', '🇸🇹'),
  Country(160, 'São Vicente e Granadinas', '🇻🇨'),
  Country(161, 'Seicheles', '🇸🇨'),
  Country(162, 'Senegal', '🇸🇳'),
  Country(163, 'Serra Leoa', '🇸🇱'),
  Country(164, 'Sérvia', '🇷🇸'),
  Country(165, 'Singapura', '🇸🇬'),
  Country(166, 'Síria', '🇸🇾'),
  Country(167, 'Somália', '🇸🇴'),
  Country(168, 'Sri Lanka', '🇱🇰'),
  Country(169, 'Sudão', '🇸🇩'),
  Country(170, 'Sudão do Sul', '🇸🇸'),
  Country(171, 'Suécia', '🇸🇪'),
  Country(172, 'Suíça', '🇨🇭'),
  Country(173, 'Suriname', '🇸🇷'),
  Country(174, 'Tailândia', '🇹🇭'),
  Country(175, 'Tajiquistão', '🇹🇯'),
  Country(176, 'Tanzânia', '🇹🇿'),
  Country(177, 'Timor-Leste', '🇹🇱'),
  Country(178, 'Togo', '🇹🇬'),
  Country(179, 'Tonga', '🇹🇴'),
  Country(180, 'Trindade e Tobago', '🇹🇹'),
  Country(181, 'Tunísia', '🇹🇳'),
  Country(182, 'Turcomenistão', '🇹🇲'),
  Country(183, 'Turquia', '🇹🇷'),
  Country(184, 'Tuvalu', '🇹🇻'),
  Country(185, 'Ucrânia', '🇺🇦'),
  Country(186, 'Uganda', '🇺🇬'),
  Country(187, 'Uruguai', '🇺🇾'),
  Country(188, 'Uzbequistão', '🇺🇿'),
  Country(189, 'Vanuatu', '🇻🇺'),
  Country(190, 'Vaticano', '🇻🇦'),
  Country(191, 'Venezuela', '🇻🇪'),
  Country(192, 'Vietnã', '🇻🇳'),
  Country(193, 'Zâmbia', '🇿🇲'),
  Country(194, 'Zimbábue', '🇿🇼'),
];
